# Generated by Django 4.2.17 on 2024-12-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='County',
            new_name='county',
        ),
    ]
